pipeline {
    agent {
        node {
            label ''
            customWorkspace "C:\\Users\\Finn\\OneDrive\\Desktop\\WorkspaceLOL"
        }
    }
    stages {
        stage('Checkout Scm') {
            steps {
                git 'https://github.com/how2fps/y2s2devops'
            }
        }

        stage('Build') {
            steps {
                bat 'mvn clean install test'
            }
        }

        stage('Deploying Application to Tomcat') {
            steps {
                bat "copy target\\devopsproject-0.0.1-SNAPSHOT.war C:\\Users\\Finn\\OneDrive\\Desktop\\DevOps\\apache-tomcat-9.0.58\\webapps\\devopsproject.war"
            }
        }

        stage('Starting Tomcat Server') {
            steps {
                bat "C:\\Users\\Finn\\OneDrive\\Desktop\\DevOps\\apache-tomcat-9.0.58\\bin\\startup.bat"
            }
        }
    }
    tools {
        maven 'maven 3.8.2'
        jdk 'JDK 1.8'
    }
    post {
        always {
            echo 'No converter for Publisher: hudson.plugins.deploy.DeployPublisher'
        }
    }
    triggers {
        pollSCM('H * * * *')
    }
}
