pipeline {
  agent {
     node { 
        label ''
        customWorkspace "C:\\Users\\User\\Documents\\DevopsPart2JenkinsWorkspace"
        } 
  }
  stages {
    stage('Checkout Scm') {
      steps {
        git(url: 'https://github.com/how2fps/y2s2devops.git', credentialsId: 'd3d9dd13-bc35-4bf2-aff4-8b3583b66acc')
      }
    }

    stage('Maven Build 0') {
      steps {
        bat 'mvn clean install -DskipTests=true'
      }
    }
    
    stage('Deploying Application to Tomcat'){
      steps {
        bat "copy target\\devopsproject-0.0.1-SNAPSHOT.war C:\\Users\\User\\Downloads\\apache-tomcat-9.0.58\\apache-tomcat-9.0.58\\webapps\\devopsproject.war"
      }
    }

    stage('Starting Tomcat Server'){
      steps{
        bat "C:\\Users\\User\\Downloads\\apache-tomcat-9.0.58\\apache-tomcat-9.0.58\\webapps\\startup.bat"
      }    
    }

  }
  tools {
    maven 'maven 3.8.2'
    jdk 'JDK 1.8'
  }
  post {
    always {
      echo 'No converter for Publisher: hudson.plugins.deploy.DeployPublisher'
    }

  }
  triggers {
    pollSCM('* * * * *')
  }
}